### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by aldegoeij** [New10/RCode#1]
Hi! We are a startup in the Netherlands under the name New10.

I see you are not using the repo's under your account recently, would you be willing to allow us to use the name New10 as organization? Feel free to drop me a mail!

Hope you are willing to help us out!

Regards,

Alexander (alexander.de.goeij@new10.com)

**Comment by New10** [comment]
I've not used the repo recently as I've been busy with other projects, but
do plan to resume it at a later date. Sorry, best of luck to you and your
business.

JN

**Comment by aldegoeij** [comment]
Ok, thanks for the quick response, best of luck to you too!
